checks:
  php:
    avoid_fixme_comments: true
    avoid_todo_comments: true
    avoid_perl_style_comments: true
    encourage_single_quotes: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
    return_doc_comments: true
    newline_at_end_of_file: true
    no_goto: true
    parameter_doc_comments: true
    return_doc_comment_if_not_inferrable: true

filter:
  paths: ['src/*']
  excluded_paths:
    - tests/*
