language: php
dist: trusty
sudo: required

mysql:
  database: travis_db
  username: root
  encoding: utf8mb4

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update --prefer-dist
  - mysqld --version

script:
  - composer test
